language: cpp
compiler:
        - gcc

sudo: false

addons:
  apt:
      packages:
        - cmake
        - freeglut3-dev
        - libfreeimage3
        - libfreeimage-dev
        - libassimp-dev
        - libglew-dev
        - libxmu-dev
        - libxi-dev

before_script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE:STRING=Debug ..
script: make