language: cpp
compiler:
        - gcc
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y software-properties-common freeglut3-dev libfreeimage3 libfreeimage-dev libassimp-dev libglw1-mesa-dev libglew-dev libxmu-dev libxi-dev
        - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
        - sudo apt-get update -qq
        - sudo apt-get install -y cmake
before_script:
        - mkdir -p build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE:STRING=Debug ..
script: make